version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: live
  open-pull-requests-limit: 10
  reviewers:
    - "pvsaintpe"
  assignees:
    - "pvsaintpe"
  labels:
    - "type:build"
