type:build:
  - ".github/**/*"
  - ".coveralls.yml"
  - "phpunit.github.xml"
  - ".gitignore"
  - "ecs.yml"
  - "phpcs.xml"

dependencies:
  - "composer.json"
  - "composer.lock"

type:helper:
  - "src/Helpers/**/*"
  - "src/Traits/**/*"

type:collections:
  - "src/Collections/**/*"

type:providers:
  - "src/Providers/**/*"
  - "src/Schema/**/*"
  - "src/Types/**/*"
  - "src/LTreeExtension.php"

type:resources:
  - "src/Resources/**/*"

type:relations:
  - "src/Relations/**/*"

type:services:
  - "src/Services/**/*"
  - "src/Exceptions/**/*"

type:interfaces:
  - "src/Interfaces/**/*"

type:tests:
  - 'tests/**/*'
  - 'phpunit.xml.dist'
  - 'tests.sh'

theme:docs:
  - "README.md"
  - "LICENSE"
  - "CONTRIBUTING.md"
  - "CODE_OF_CONDUCT.md"
  - "src/.meta.php"
