name: CI	

on:	
  push:	
  pull_request:	

env:	
  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}	
  COVERAGE: '0'	

jobs:	
  php-linter-fixer:	  
    runs-on: ubuntu-latest	   
    timeout-minutes: 20	
    strategy:	
      matrix:	
        php:	
          - '7.3'	
      fail-fast: false	
    env:	
      PHP_CS_FIXER_FUTURE_MODE: '1'	
    steps:	
      - name: Checkout	
        uses: actions/checkout@v2	
      - name: Setup PHP	
        uses: shivammathur/setup-php@v2	
        with:	
          php-version: ${{ matrix.php }}	
          extensions: pcov, pgsql 
          ini-values: memory_limit=-1	
          tools: pecl, composer
          coverage: none	
      - name: Run linter
        run: |
          rm composer.lock
          composer -n update
          vendor/bin/ecs check --config=ecs.yml .
