name: CI	

on:	
  push:
  pull_request:

env:	
  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}	
  COVERAGE: '1'
  working_directory: ./src
  php_extensions: 'apcu, bcmath, ctype, curl, dom, iconv, intl, json, mbstring, opcache, openssl, pdo, pdo_pgsql, pcntl, pcov, posix, redis, session, simplexml, sockets, tokenizer, xml, xmlwriter, zip'
  key: cache-v0.1
  DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/application?charset=UTF-8'
  REDIS_URL: 'redis://localhost:6379'

jobs:	
  lint:
    runs-on: '${{ matrix.operating_system }}'
    timeout-minutes: 20	
    strategy:	
      matrix:
        operating_system:
          - ubuntu-latest
        php_versions:
          - '7.4'
      fail-fast: false
    env:	
      PHP_CS_FIXER_FUTURE_MODE: '0'
    name: 'Lint / PHP ${{ matrix.php_versions }} @ ${{ matrix.operating_system }}'
    steps:	
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup cache environment'
        id: cache-env
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '${{ matrix.php_versions }}'
          extensions: '${{ env.php_extensions }}'
          key: '${{ env.key }}'
      - name: 'Cache extensions'
        uses: actions/cache@v1
        with:
          path: '${{ steps.cache-env.outputs.dir }}'
          key: '${{ steps.cache-env.outputs.key }}'
          restore-keys: '${{ steps.cache-env.outputs.key }}'
      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2	
        with:	
          php-version: ${{ matrix.php_versions }}
          extensions: '${{ env.php_extensions }}'
          ini-values: memory_limit=-1	
          tools: pecl, composer
          coverage: none
      - name: 'Setup problem matchers for PHP (aka PHP error logs)'
        run: 'echo "::add-matcher::${{ runner.tool_cache }}/php.json"'
      - name: 'Setup problem matchers for PHPUnit'
        run: 'echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"'
      - name: 'Get Composer cache directory'
        id: composer-cache
        run: 'echo "::set-output name=dir::$(composer config cache-files-dir)"'
        working-directory: '${{env.working_directory}}'
      - name: 'Cache dependencies'
        uses: actions/cache@v1
        with:
          path: '${{ steps.composer-cache.outputs.dir }}'
          key: '${{ runner.os }}-composer-${{ hashFiles(''**/composer.lock'') }}'
          restore-keys: '${{ runner.os }}-composer-'
      - name: 'Validate composer.json and composer.lock'
        run: 'composer validate'
        working-directory: '${{env.working_directory}}'
      - name: 'Install PHP dependencies with Composer'
        run: 'composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader'
        working-directory: '${{env.working_directory}}'
      - name: 'Linting PHP source files'
        run: 'vendor/bin/ecs check --config=ecs.yml .'
